# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1130, 552)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(30, 100, 721, 101))
        self.textEdit.setObjectName("textEdit")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(30, 320, 721, 201))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 80, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 300, 72, 15))
        self.label_2.setObjectName("label_2")
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(30, 30, 211, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(Form)
        self.textEdit_3.setGeometry(QtCore.QRect(520, 30, 231, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(Form)
        self.textEdit_4.setGeometry(QtCore.QRect(270, 30, 231, 31))
        self.textEdit_4.setObjectName("textEdit_4")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 10, 72, 15))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(270, 10, 72, 15))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(520, 10, 81, 16))
        self.label_5.setObjectName("label_5")
        self.textEdit_5 = QtWidgets.QTextEdit(Form)
        self.textEdit_5.setGeometry(QtCore.QRect(30, 250, 104, 31))
        self.textEdit_5.setObjectName("textEdit_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(30, 230, 72, 15))
        self.label_6.setObjectName("label_6")
        self.textEdit_6 = QtWidgets.QTextEdit(Form)
        self.textEdit_6.setGeometry(QtCore.QRect(190, 250, 91, 31))
        self.textEdit_6.setObjectName("textEdit_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(190, 230, 72, 15))
        self.label_7.setObjectName("label_7")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(810, 30, 91, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(967, 30, 111, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(900, 300, 181, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(800, 300, 81, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(800, 350, 81, 16))
        self.label_9.setObjectName("label_9")
        self.comboBox_2 = QtWidgets.QComboBox(Form)
        self.comboBox_2.setGeometry(QtCore.QRect(900, 350, 181, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(800, 250, 71, 20))
        self.label_10.setObjectName("label_10")
        self.comboBox_3 = QtWidgets.QComboBox(Form)
        self.comboBox_3.setGeometry(QtCore.QRect(900, 250, 181, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(800, 200, 72, 15))
        self.label_11.setObjectName("label_11")
        self.comboBox_4 = QtWidgets.QComboBox(Form)
        self.comboBox_4.setGeometry(QtCore.QRect(900, 200, 83, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_2.setGeometry(QtCore.QRect(330, 250, 291, 31))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.comboBox_5 = QtWidgets.QComboBox(Form)
        self.comboBox_5.setGeometry(QtCore.QRect(900, 400, 181, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(800, 400, 91, 20))
        self.label_12.setObjectName("label_12")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(650, 250, 101, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(330, 230, 72, 15))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(810, 450, 54, 21))
        self.label_15.setObjectName("label_15")
        self.comboBox_6 = QtWidgets.QComboBox(Form)
        self.comboBox_6.setGeometry(QtCore.QRect(900, 450, 69, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_7 = QtWidgets.QComboBox(Form)
        self.comboBox_7.setGeometry(QtCore.QRect(990, 520, 121, 22))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(930, 520, 54, 20))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(30, 530, 251, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(470, 530, 301, 20))
        self.label_18.setObjectName("label_18")
        self.textEdit_7 = QtWidgets.QTextEdit(Form)
        self.textEdit_7.setGeometry(QtCore.QRect(800, 120, 321, 21))
        self.textEdit_7.setObjectName("textEdit_7")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(800, 100, 54, 12))
        self.label_13.setObjectName("label_13")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(800, 160, 54, 12))
        self.label_19.setObjectName("label_19")
        self.textEdit_8 = QtWidgets.QTextEdit(Form)
        self.textEdit_8.setGeometry(QtCore.QRect(900, 150, 111, 31))
        self.textEdit_8.setObjectName("textEdit_8")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "token"))
        self.label_2.setText(_translate("Form", "后台"))
        self.label_3.setText(_translate("Form", "设备ID"))
        self.label_4.setText(_translate("Form", "用户ID"))
        self.label_5.setText(_translate("Form", "限制最高价"))
        self.label_6.setText(_translate("Form", "购买索引"))
        self.label_7.setText(_translate("Form", "交易密码"))
        self.pushButton.setText(_translate("Form", "上传信息"))
        self.pushButton_2.setText(_translate("Form", "开始"))
        self.comboBox.setItemText(0, _translate("Form", "f40597048a7ee04f"))
        self.comboBox.setItemText(1, _translate("Form", "90693f5be4feb9d4"))
        self.comboBox.setItemText(2, _translate("Form", "无"))
        self.label_8.setText(_translate("Form", "预设设备ID"))
        self.label_9.setText(_translate("Form", "预设用户ID"))
        self.comboBox_2.setItemText(0, _translate("Form", "1650388318539"))
        self.comboBox_2.setItemText(1, _translate("Form", "1651418691298"))
        self.comboBox_2.setItemText(2, _translate("Form", "1648214508076"))
        self.comboBox_2.setItemText(3, _translate("Form", "无"))
        self.label_10.setText(_translate("Form", "预设价格"))
        self.comboBox_3.setItemText(0, _translate("Form", "50"))
        self.comboBox_3.setItemText(1, _translate("Form", "100"))
        self.comboBox_3.setItemText(2, _translate("Form", "300"))
        self.comboBox_3.setItemText(3, _translate("Form", "500"))
        self.comboBox_3.setItemText(4, _translate("Form", "1000"))
        self.comboBox_3.setItemText(5, _translate("Form", "无"))
        self.label_11.setText(_translate("Form", "预设索引"))
        self.comboBox_4.setItemText(0, _translate("Form", "1号相册"))
        self.comboBox_4.setItemText(1, _translate("Form", "2号相册"))
        self.comboBox_4.setItemText(2, _translate("Form", "3号相册"))
        self.comboBox_4.setItemText(3, _translate("Form", "4号相册"))
        self.comboBox_4.setItemText(4, _translate("Form", "5号相册"))
        self.comboBox_4.setItemText(5, _translate("Form", "6号相册"))
        self.comboBox_4.setItemText(6, _translate("Form", "7号相册"))
        self.comboBox_4.setItemText(7, _translate("Form", "无"))
        self.comboBox_5.setItemText(0, _translate("Form", "095732"))
        self.comboBox_5.setItemText(1, _translate("Form", "无"))
        self.label_12.setText(_translate("Form", "预设交易密码"))
        self.pushButton_3.setText(_translate("Form", "查看索引信息"))
        self.label_14.setText(_translate("Form", "索引信息"))
        self.label_15.setText(_translate("Form", "线程数"))
        self.comboBox_6.setItemText(0, _translate("Form", "2"))
        self.comboBox_6.setItemText(1, _translate("Form", "3"))
        self.comboBox_6.setItemText(2, _translate("Form", "5"))
        self.comboBox_6.setItemText(3, _translate("Form", "8"))
        self.comboBox_6.setItemText(4, _translate("Form", "10"))
        self.comboBox_6.setItemText(5, _translate("Form", "15"))
        self.comboBox_6.setItemText(6, _translate("Form", "20"))
        self.comboBox_6.setItemText(7, _translate("Form", "25"))
        self.comboBox_6.setItemText(8, _translate("Form", "30"))
        self.comboBox_6.setItemText(9, _translate("Form", "40"))
        self.comboBox_6.setItemText(10, _translate("Form", "50"))
        self.comboBox_6.setItemText(11, _translate("Form", "60"))
        self.comboBox_6.setItemText(12, _translate("Form", "70"))
        self.comboBox_6.setItemText(13, _translate("Form", "80"))
        self.comboBox_7.setItemText(0, _translate("Form", "测试模式"))
        self.comboBox_7.setItemText(1, _translate("Form", "抢购模式"))
        self.comboBox_7.setItemText(2, _translate("Form", "批量抢购"))
        self.label_16.setText(_translate("Form", "模式选择"))
        self.label_17.setText(_translate("Form", "作者：西红柿炒坏蛋；QQ：761454838"))
        self.label_18.setText(_translate("Form", "免责声明：本软件仅供技术交流，请勿用于非法用途"))
        self.label_13.setText(_translate("Form", "商品代码"))
        self.label_19.setText(_translate("Form", "商品份数"))
